title: Tiny Notes - Deta Teguh Satrio
email: detatsatrio@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Web and Mobile Developer Stay Lean and Hungry
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://detatsatrio.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Deta Teguh Satrio # add your name
author-pic: deta-face.jpg
about-author: My name is Deta Teguh Satrio. Iâ€™m a full-time web and mobile developer and sport addict.

# Contact links
email: detatsatrio@outlook.com # Add your Email address
phone: 087730015246 # Add your Phone number
website: detatsatrio.github.io # Add your website, do not add http://
linkedin: detatsatrio # Add your Linkedin handle
github: detatsatrio # Add your Github handle
twitter: '@detatsatrio' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: detatsatrio # Add your Instagram handle
pinterest: detatsatrio # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: detatsatrio # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
